export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_REQUEST_SUCCESS = 'FETCH_CONTACTS_REQUEST_SUCCESS'
export const FETCH_CONTACTS_REQUEST_FAILURE = 'FETCH_CONTACTS_REQUEST_FAILURE'

export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST'
export const REMOVE_CONTACT_REQUEST_SUCCESS = 'REMOVE_CONTACT_REQUEST_SUCCESS'
export const REMOVE_CONTACT_REQUEST_FAILURE = 'REMOVE_CONTACT_REQUEST_FAILURE'

export const OPEN_CONTACT_CU_DIALOG_AS_NEW = 'OPEN_CONTACT_CU_DIALOG_AS_NEW'
export const OPEN_CONTACT_CU_DIALOG_AS_EDIT = 'OPEN_CONTACT_CU_DIALOG_AS_EDIT'
export const CLOSE_CONTACT_CU_DIALOG = 'CLOSE_CONTACT_CU_DIALOG'

export const SAVE_NEW_CONTACT_REQUEST = 'SAVE_NEW_CONTACT_REQUEST'
export const SAVE_NEW_CONTACT_REQUEST_SUCCESS = 'SAVE_NEW_CONTACT_REQUEST_SUCCESS'
export const SAVE_NEW_CONTACT_REQUEST_FAILURE = 'SAVE_NEW_CONTACT_REQUEST_FAILURE'

export const FILTER_CONTACTS = 'FILTER_CONTACTS'