export const ADD_CONTACT = 'ADD_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const FILTER_CONTACT = 'FILTER_CONTACT'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_REQUEST_SUCCESS = 'FETCH_CONTACTS_REQUEST_SUCCESS'
export const FETCH_CONTACTS_REQUEST_FAILURE = 'FETCH_CONTACTS_REQUEST_FAILURE'

export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST'
export const REMOVE_CONTACT_REQUEST_SUCCESS = 'REMOVE_CONTACT_REQUEST_SUCCESS'
export const REMOVE_CONTACT_REQUEST_FAILURE = 'REMOVE_CONTACT_REQUEST_FAILURE'